ls:
  src/**:
    .js: kebab-case | PascalCase
    .ts: kebab-case | PascalCase
    .tsx: kebab-case | PascalCase
    .vue: kebab-case | PascalCase
    .less: kebab-case
    .spec.js: kebab-case

  types:
    .d.ts: kebab-case

ignore:
  - src/locale/lang
